### ISSUE TITLE
delete_people method not working

### ISSUE THREAD

**Issue by ciacicode** [mixpanel/mixpanel-utils#21]
I just tried to use the delete_people method to no avail.

```
from mixpanel_api import Mixpanel
mixpanel = Mixpanel('mysecret','mytoken')

mixpanel.people_delete(query_params={ 'selector' : '(("olddomain.com" in properties["$email"]) and (defined (properties["$email"])))'})
```
The backup file is correctly generated, and there is the right number of profiles in it, yet when I go to mixpanel UI and try to do the same query to see if the profiles were actually deleted, I get the same count. The script runs fine with no errors.

**Comment by LaithAmmouri** [comment]
same here

**Comment by anisha-rohra** [comment]
Having the same problem

**Comment by LaithAmmouri** [comment]
You are welcome! Yup, it should take time, logically the results should be cached in the platform. Please let me know if the users are not deleted to dig more in the case.

Cheers

**Comment by jaredmixpanel** [comment]
It does take time on the backend for the $delete operations to be processed. As long as you're getting successful API responses the python code for this module is not likely to be the problem. If the issue persists however and you're confident the problem is the python code making the API calls, please re-open the issue with further detail.
